# Generated by Django 3.0 on 2025-06-19 00:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20250619_0504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryorder',
            name='assigned_at',
        ),
        migrations.RemoveField(
            model_name='deliveryorder',
            name='delivered_at',
        ),
        migrations.RemoveField(
            model_name='deliveryorder',
            name='delivery_status',
        ),
        migrations.RemoveField(
            model_name='deliveryorder',
            name='order',
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='address',
            field=models.TextField(default='Unknown'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='assigned_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='customer_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='order_id',
            field=models.CharField(default='UNKNOWN123', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='status',
            field=models.CharField(choices=[('Assigned', 'Assigned'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Failed', 'Failed')], default='Assigned', max_length=30),
        ),
    ]
